### ISSUE TITLE
Add one CVPR paper

### ISSUE THREAD

**Issue by wangjksjtu** [52CV/CVPR-2021-Papers#13]
Hi, 

Thanks for your amazing collection of CVPR papers! Could you please add this paper AdvSim: Generating Safety-Critical Scenarios for Self-Driving Vehicles (https://arxiv.org/abs/2101.06549), this can be tagged as simulation, adversarial example, or self-driving / robotics paper.

Thanks.

**Comment by 52CV** [comment]
Thanks！
