### ISSUE TITLE
Add one oral paper (video person re-id)

### ISSUE THREAD

**Issue by zkcys001** [52CV/CVPR-2021-Papers#16]
Hi,

Thanks for your great collections! Could you please add this paper: Spatial-Temporal Correlation and Topology Learning
for Person Re-Identification in Videos, Jiawei Liu, Zheng-Jun Zha, Wei Wu, Kecheng Zheng, Qibin Sun(https://arxiv.org/pdf/2104.08241.pdf), which has appeared at CVPR 2021 as an oral paper.

Thanks.

**Comment by 52CV** [comment]
OK，thanks～
