### ISSUE TITLE
請教一下您是如何尋找被CVPR Accept的paper呢?

### ISSUE THREAD

**Issue by ew66** [52CV/CVPR-2021-Papers#17]
您好，感謝你分享這些有用的資訊!

想跟你請教一下，目前CVPR只有release出accepted paper index，想請問您是怎麼搜集到這些index對應到的論文呢?

**Comment by 52CV** [comment]
您好，arxiv或者作者主页上声明的。

**Comment by ew66** [comment]
感謝分享!
