### ISSUE TITLE
Update a paper

### ISSUE THREAD

**Issue by Finspire13** [52CV/CVPR-2021-Papers#20]
Hi, thanks for your awesome collection! Could you please update the paper "Towards Unified Surgical Skill Assessment":

Paper: https://arxiv.org/abs/2106.01035
Code: https://github.com/Finspire13/Towards-Unified-Surgical-Skill-Assessment
Category: Medical Imaging(医学影像)

Thanks!

**Comment by 52CV** [comment]
OK ~ Thanks!
