### ISSUE TITLE
Please add one CVPR paper

### ISSUE THREAD

**Issue by sangmin-git** [52CV/CVPR-2021-Papers#21]
Thanks for your nice collection! Could you please update the following paper.

Video Prediction Recalling Long-term Motion Context via Memory Alignment Learning (CVPR 2021 ORAL)
Paper link: https://arxiv.org/abs/2104.00924
Code link: https://github.com/sangmin-git/LMC-Memory

Thank you.

**Comment by 52CV** [comment]
OK，Thanks~
