### ISSUE TITLE
Add one new paper in object detection~

### ISSUE THREAD

**Issue by implus** [52CV/CVPR-2021-Papers#3]
Generalized Focal Loss V2: Learning Reliable Localization Quality Estimation for Dense Object Detection

Paper: https://arxiv.org/abs/2011.12885
Code: https://github.com/implus/GFocalV2
Zhihu: https://zhuanlan.zhihu.com/p/147691786

**Comment by implus** [comment]
Thanks a lot~

**Comment by 52CV** [comment]
My pleasure~
