### ISSUE TITLE
Please add an accepted paper

### ISSUE THREAD

**Issue by wjfwzzc** [52CV/CVPR-2021-Papers#4]
Hi,
Could you add our CVPR2021 paper to "Object Detection" topic:

Title: End-to-End Object Detection with Fully Convolutional Network
Paper: <https://arxiv.org/abs/2012.03544>
Code: <https://github.com/Megvii-BaseDetection/DeFCN>
Zhihu: <https://zhuanlan.zhihu.com/p/332281368>

Thanks!

**Comment by 52CV** [comment]
收到
